//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SectionTwoMainPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SectionTwoMainPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SectionTwoMainPage", typeof(SectionTwoMainPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Code.
        /// </summary>
        public static string CleanCode {
            get {
                return ResourceManager.GetString("CleanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely principled and standard coding and commenting of all the required parts of this format has distinguished it from others..
        /// </summary>
        public static string CleanCodeText {
            get {
                return ResourceManager.GetString("CleanCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string MoreButton {
            get {
                return ResourceManager.GetString("MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully responsive.
        /// </summary>
        public static string Responsive {
            get {
                return ResourceManager.GetString("Responsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have the best display on any device. It doesn&apos;t matter if you are using a mobile phone, tablet or computer..
        /// </summary>
        public static string ResponsiveText {
            get {
                return ResourceManager.GetString("ResponsiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application in the shortest time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily and in less than a few minutes, use this completely ready and standard template in your projects..
        /// </summary>
        public static string TimeText {
            get {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }
    }
}
